feat(bin): move most scripts to strict POSIX

diff --git a/bin/.local/bin/git_grep_modified_files b/bin/.local/bin/git_grep_modified_files
--- a/bin/.local/bin/git_grep_modified_files
+++ b/bin/.local/bin/git_grep_modified_files
@@ -1,12 +1,12 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
-set -euo pipefail
-IFS=$'\n\t'
+set -eu
+IFS=$(print '\n\t')
 
 [ "$#" -eq 1 ] || {
-    usage
-    echo >&2 "1 argument required, $# provided"
-    exit 1
+	usage
+	echo >&2 "1 argument required, $# provided"
+	exit 1
 }
 
 # Grep with extended regexp + ignore case through all the modified files
diff --git a/bin/.local/bin/git_grep_modified_lines b/bin/.local/bin/git_grep_modified_lines
--- a/bin/.local/bin/git_grep_modified_lines
+++ b/bin/.local/bin/git_grep_modified_lines
@@ -1,12 +1,14 @@
 #!/usr/bin/env bash
+#
+# TODO: migrate this to POSIX shell
 
 set -euo pipefail
 IFS=$'\n\t'
 
 [ "$#" -eq 1 ] || {
-    usage
-    echo >&2 "1 argument required, $# provided"
-    exit 1
+	usage
+	echo >&2 "1 argument required, $# provided"
+	exit 1
 }
 
 # TODO: finish this up
@@ -20,10 +22,10 @@ IFS=$'\n\t'
 #     # git --no-pager diff HEAD $file | grep -iE "$1"
 # done
 
-for file in $(git ls-files -com --exclude-standard); do
-    if test "$#" = 0; then
-        git --no-pager diff --no-index -- /dev/null "$file" | grep -iE "TODO"
-    else
-        git --no-pager diff "$file" | grep -iE "TODO"
-    fi
+for file in "$(git ls-files -com --exclude-standard)"; do
+	if test "$#" = 0; then
+		git --no-pager diff --no-index -- /dev/null "$file" | grep -iE "TODO"
+	else
+		git --no-pager diff "$file" | grep -iE "TODO"
+	fi
 done
